### ISSUE TITLE
Impossible to insert units in "TRUCK II"

### ISSUE THREAD

**Issue by funtimeandrefoxy** [AcidCaos/socialwarriors#11]
In the last mission of the first world, there is a vehicle called "TRUCK II" that can store up to 6 units. But it is impossible to insert any unit inside it.
![image](https://github.com/AcidCaos/socialwarriors/assets/59577497/4b52abd4-263e-4e7e-9285-03feb0dc4790)

**Comment by Nerroth** [comment]
Only some units like the soldiers are able to enter the truck on that mission. This isn't a bug.
