### ISSUE TITLE
the discord link is broken

### ISSUE THREAD

**Issue by nidara300703** [AcidCaos/socialwarriors#5]
the link only gos to discord not the discord server.
(i dont know the name of the server so i cant find it)

**Comment by Mohamedallouha** [comment]
looks like the developer has passed away

{donno just saying}

**Comment by Nerroth** [comment]
Hi.

The issue has been fixed and the link works now, it should be [https://discord.gg/zW5gSbQJBw](https://discord.gg/zW5gSbQJBw)
