### ISSUE TITLE
Ayuda, Social Wars ya no me carga

### ISSUE THREAD

**Issue by oerosales** [AcidCaos/socialwarriors#6]
Quise probar un hack y me salió mal, edité un archivo para tener todos los recursos al máximo y al parecer cuando me carga el código me sale error, ya no me abre en mi GooglePortable, me sale como error. Lo desinstale varias veces tanto la app de social wars y GooglePortable y nada, porfavor, que alguien me brinde ayuda, que puedo hacer.

**Comment by Nerroth** [comment]
Hi.

Since this isn't an issue, I will be closing it. 

However the community can help you with this on our [Discord](https://discord.gg/zW5gSbQJBw) so feel free to join it.
