### ISSUE TITLE
Atom Fusion Error

### ISSUE THREAD

**Issue by Mohamedallouha** [AcidCaos/socialwarriors#7]
![Untitled](https://github.com/AcidCaos/socialwarriors/assets/63161724/72b0fdd0-8c52-4338-9769-c26b0075ec95)

![2](https://github.com/AcidCaos/socialwarriors/assets/63161724/9ec72fef-8fad-4085-a941-b301eaabb022)

Warriors are not showing up
and the Atom Fusion appears as a tent

any help??

**Comment by Nerroth** [comment]
Hi.

We're aware of the issue with Atom Fusion, however a fix for this doesn't currently exist as it requires more reverse engineering. You'll just have to be patient and wait for us to fix it in the future.
